import type { Metadata } from "next";
import "@/public/css/globals.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
      >
        {children}
      </body>
    </html>
  );
}
